{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0b37d52d",
   "metadata": {},
   "outputs": [],
   "source": [
    "DROP TABLE if exists d_date;\n",
    "\n",
    "CREATE TABLE d_date\n",
    "(\n",
    "  date_dim_id              INT NOT NULL,\n",
    "  date_actual              DATE NOT NULL,\n",
    "  epoch                    BIGINT NOT NULL,\n",
    "  day_suffix               VARCHAR(4) NOT NULL,\n",
    "  day_name                 VARCHAR(9) NOT NULL,\n",
    "  day_of_week              INT NOT NULL,\n",
    "  day_of_month             INT NOT NULL,\n",
    "  day_of_quarter           INT NOT NULL,\n",
    "  day_of_year              INT NOT NULL,\n",
    "  week_of_month            INT NOT NULL,\n",
    "  week_of_year             INT NOT NULL,\n",
    "  week_of_year_iso         CHAR(10) NOT NULL,\n",
    "  month_actual             INT NOT NULL,\n",
    "  month_name               VARCHAR(9) NOT NULL,\n",
    "  month_name_abbreviated   CHAR(3) NOT NULL,\n",
    "  quarter_actual           INT NOT NULL,\n",
    "  quarter_name             VARCHAR(9) NOT NULL,\n",
    "  year_actual              INT NOT NULL,\n",
    "  first_day_of_week        DATE NOT NULL,\n",
    "  last_day_of_week         DATE NOT NULL,\n",
    "  first_day_of_month       DATE NOT NULL,\n",
    "  last_day_of_month        DATE NOT NULL,\n",
    "  first_day_of_quarter     DATE NOT NULL,\n",
    "  last_day_of_quarter      DATE NOT NULL,\n",
    "  first_day_of_year        DATE NOT NULL,\n",
    "  last_day_of_year         DATE NOT NULL,\n",
    "  mmyyyy                   CHAR(6) NOT NULL,\n",
    "  mmddyyyy                 CHAR(10) NOT NULL,\n",
    "  weekend_indr             BOOLEAN NOT NULL\n",
    ");\n",
    "\n",
    "ALTER TABLE public.d_date ADD CONSTRAINT d_date_date_dim_id_pk PRIMARY KEY (date_dim_id);\n",
    "\n",
    "CREATE INDEX d_date_date_actual_idx\n",
    "  ON d_date(date_actual);\n",
    "\n",
    "COMMIT;\n",
    "\n",
    "INSERT INTO d_date\n",
    "SELECT TO_CHAR(datum, 'yyyymmdd')::INT AS date_dim_id,\n",
    "       datum AS date_actual,\n",
    "       EXTRACT(EPOCH FROM datum) AS epoch,\n",
    "       TO_CHAR(datum, 'fmDDth') AS day_suffix,\n",
    "       TO_CHAR(datum, 'TMDay') AS day_name,\n",
    "       EXTRACT(ISODOW FROM datum) AS day_of_week,\n",
    "       EXTRACT(DAY FROM datum) AS day_of_month,\n",
    "       datum - DATE_TRUNC('quarter', datum)::DATE + 1 AS day_of_quarter,\n",
    "       EXTRACT(DOY FROM datum) AS day_of_year,\n",
    "       TO_CHAR(datum, 'W')::INT AS week_of_month,\n",
    "       EXTRACT(WEEK FROM datum) AS week_of_year,\n",
    "       EXTRACT(ISOYEAR FROM datum) || TO_CHAR(datum, '\"-W\"IW-') || EXTRACT(ISODOW FROM datum) AS week_of_year_iso,\n",
    "       EXTRACT(MONTH FROM datum) AS month_actual,\n",
    "       TO_CHAR(datum, 'TMMonth') AS month_name,\n",
    "       TO_CHAR(datum, 'Mon') AS month_name_abbreviated,\n",
    "       EXTRACT(QUARTER FROM datum) AS quarter_actual,\n",
    "       CASE\n",
    "           WHEN EXTRACT(QUARTER FROM datum) = 1 THEN 'First'\n",
    "           WHEN EXTRACT(QUARTER FROM datum) = 2 THEN 'Second'\n",
    "           WHEN EXTRACT(QUARTER FROM datum) = 3 THEN 'Third'\n",
    "           WHEN EXTRACT(QUARTER FROM datum) = 4 THEN 'Fourth'\n",
    "           END AS quarter_name,\n",
    "       EXTRACT(YEAR FROM datum) AS year_actual,\n",
    "       datum + (1 - EXTRACT(ISODOW FROM datum))::INT AS first_day_of_week,\n",
    "       datum + (7 - EXTRACT(ISODOW FROM datum))::INT AS last_day_of_week,\n",
    "       datum + (1 - EXTRACT(DAY FROM datum))::INT AS first_day_of_month,\n",
    "       (DATE_TRUNC('MONTH', datum) + INTERVAL '1 MONTH - 1 day')::DATE AS last_day_of_month,\n",
    "       DATE_TRUNC('quarter', datum)::DATE AS first_day_of_quarter,\n",
    "       (DATE_TRUNC('quarter', datum) + INTERVAL '3 MONTH - 1 day')::DATE AS last_day_of_quarter,\n",
    "       TO_DATE(EXTRACT(YEAR FROM datum) || '-01-01', 'YYYY-MM-DD') AS first_day_of_year,\n",
    "       TO_DATE(EXTRACT(YEAR FROM datum) || '-12-31', 'YYYY-MM-DD') AS last_day_of_year,\n",
    "       TO_CHAR(datum, 'mmyyyy') AS mmyyyy,\n",
    "       TO_CHAR(datum, 'mmddyyyy') AS mmddyyyy,\n",
    "       CASE\n",
    "           WHEN EXTRACT(ISODOW FROM datum) IN (6, 7) THEN TRUE\n",
    "           ELSE FALSE\n",
    "           END AS weekend_indr\n",
    "FROM (SELECT '1970-01-01'::DATE + SEQUENCE.DAY AS datum\n",
    "      FROM GENERATE_SERIES(0, 29219) AS SEQUENCE (DAY)\n",
    "      GROUP BY SEQUENCE.DAY) DQ\n",
    "ORDER BY 1;\n",
    "\n",
    "COMMIT;"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
